sudo: false
dist: bionic
language: python
addons:
  apt:
    # sources:
    #   - sourceline: "ppa:jonathonf/ffmpeg-4"
    packages:
      - python-dev
      - pkg-config
      - libudev-dev
      - libavformat-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavutil-dev
      - libswscale-dev
      - libavresample-dev
      - libswresample-dev
      - libavfilter-dev
python:
  - "3.7"
before_install:
  - mv travis/travis_secrets.yaml secrets.yaml
  - mv travis/travis.fake_ssl_crt travis.fake_ssl_crt
  - mv travis/travis.fake_ssl_key travis.fake_ssl_key
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
