dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - mv travis/travis_secrets.yaml secrets.yaml
  - mv travis/travis.fake_ssl_crt travis.fake_ssl_crt
  - mv travis/travis.fake_ssl_key travis.fake_ssl_key
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install git+git://github.com/home-assistant/home-assistant.git@dev
script:
  - hass -c . --script check_config
