###################################################
#     Home Assistant Main Configuration File      #
###################################################
homeassistant:
  name: Home Assistant
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: !secret evelation_loc_home
  time_zone: Europe/London
  temperature_unit: C
  unit_system: metric
  customize_glob: !include config/customize_glob.yaml
  customize: !include config/customize.yaml

  # https://home-assistant.io/docs/configuration/packages/  
  packages: !include_dir_named packages

####################################################
#                    Components                    #
####################################################
automation: !include config/automation.yaml
discovery: !include config/discovery.yaml
dyson: !include config/dyson.yaml
group: !include config/group.yaml
http: !include config/http.yaml
history: !include config/history.yaml
logbook: !include config/logbook.yaml
logger: !include config/logger.yaml
mqtt: !include config/mqtt.yaml
notify: !include config/notify.yaml
panel_iframe: !include config/iframe.yaml
recorder: !include config/recorder.yaml
rfxtrx: !include config/rfxtrx.yaml
tts: !include config/tts.yaml
zone: !include config/zone.yaml
zha: !include config/zha.yaml
zwave: !include config/zwave.yaml

# https://www.home-assistant.io/components/updater/
updater:
# https://www.home-assistant.io/components/config/
config:
# https://www.home-assistant.io/docs/ecosystem/ios/
ios:
# https://www.home-assistant.io/components/map/
map:
# https://www.home-assistant.io/components/system_health/
system_health: