# https://www.home-assistant.io/components/dyson/

username: !secret dyson_username
password: !secret dyson_password
language: GB
devices: 
  - device_id: !secret dyson_fan1_serial
    device_ip: !secret dyson_fan1_ip_address
