# https://www.home-assistant.io/components/logger/

default: warn
logs:
  homeassistant.components.zha: debug
  # homeassistant.components.nest: debug
  # homeassistant.components.binary_sensor.nest: debug
  # nest: debug
