# https://www.home-assistant.io/components/mqtt/

broker: core-mosquitto
username: !secret MQTT_username
password: !secret MQTT_password
birth_message:
  topic: "hass/status"
  payload: "online"
  qos: 1
  retain: true
will_message:
  topic: "hass/status"
  payload: "offline"
  qos: 1
  retain: true
