- id: '1500048597882'
  alias: Turn on lights in the morning and at sunset
  trigger:
    - platform: time
      at: "06:30:00"
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.lwrf_hall_socket_1 # Twigs

- id: a_morning_lights
  alias: Turn off morning lights
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      # Can be a positive or negative number
      above: 10.0
  action:
    - service: homeassistant.turn_off
      entity_id: switch.lwrf_hall_socket_1 # Twigs

- id: a_daytime_air_freshener_on
  alias: Turn on air freshener socket in the morning
  trigger:
    - platform: time
      at: "06:30:00"
  action:
    - service: homeassistant.turn_on
      entity_id: switch.lwrf_hall_socket_2 # Air Freshener

- id: a_daytime_air_freshener_off
  alias: Turn off air freshener socket at night
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: homeassistant.turn_off
      entity_id: switch.lwrf_hall_socket_2 # Air Freshener

- id: a_config_update
  alias: Update config HASS if travis build is successfull
  trigger:
    - platform: state
      entity_id: sensor.shortblokehome_assistant_config_last_build_id
  condition:
    - condition: state
      entity_id: sensor.shortblokehome_assistant_config_last_build_state
      state: 'passed'
  action:
    - service: hassio.addon_stop # Requires Git Pull is set to auto-start
      data: 
        addon: "core_git_pull"
    - delay: 0:01
    - service: hassio.addon_start
      data: 
        addon: "core_git_pull"

- id: a_Loft_Fan_On
  alias: Loft Fan Turn On When Hot
  trigger:
    - platform: numeric_state
      entity_id: sensor.loft_fan_temperature
      above: 30
  action:
    - service: homeassistant.turn_on
      entity_id: switch.sonoff_loft_fan_power

- id: a_Loft_Fan_Off
  alias: Loft Fan Turn Off When Not Hot
  trigger:
    - platform: numeric_state
      entity_id: sensor.loft_fan_temperature
      below: 30
  action:
    - service: homeassistant.turn_off
      entity_id: switch.sonoff_loft_fan_power

- id: a_hapi_low_disk
  alias: HAPi Low Disk Space Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.disk_use_percent
      above: 90
  action:
    - service: notify.ios_martins_iphone
      data: 
        title: "HAPi Low Resource Alert"
        message: "Low Disk Space > 90% Used"

- id: a_hapi_low_mem
  alias: HAPi Low Memory Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.memory_use_percent
      above: 90
  action:
    - service: notify.ios_martins_iphone
      data: 
        title: "HAPi Low Resource Alert"
        message: "Low Memory > 90% Used"

- id: a_hapi_high_load
  alias: HAPi High Load Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.load_5m
      above: 2.8 # 4 Cores in RPi3 x 0.7 per core, for relatively high sustained load = 
  action:
    - service: notify.ios_martins_iphone
      data: 
        title: "HAPi Low Resource Alert"
        message: "System Load 5m Load Average > 2.8"

- id: a_sonos_tts_test
  alias: Sonos TTS Test
  trigger:
    - platform: state
      entity_id: input_boolean.mytest
  action:
    - service: script.sonos_say
      data:
        sonos_entity: media_player.conservatory
        volume: 0.5
        message: 'This is a test of Sonos Text to Speech'
        # Delay needs to be long enough to allow text to be read aloud
        delay: '00:00:05'

- id: a_hass_update_available
  alias: 'HASS Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.ios_martins_iphone
    data:
      message: 'Update for Home Assistant is available.'

- id: a_sonos_burglar_alarm
  alias: Sonos Burglar Alarm
  trigger:
    - platform: state
      entity_id: input_boolean.mytest
  action:
    - service: script.sonos_alarm
      data:
        # Maximum Volume
        volume: 1.0
        # Duration before stopping and restoring state
        delay: '00:01:00'

- id: a_sonos_restore_snapshot
  alias: 'Sonos restore snapshot state'
  trigger:
    - platform: state
      entity_id: input_boolean.mytest
  action:
    - service: media_player.sonos_restore

- id: a_weekly_snapshot
  alias: HASSIO Weekly Snapshot (3am)
  trigger:
    - platform: time
      at: '3:00:00'
  condition:
    condition: time
    weekday:
      - sun
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}

- id: a_weekly_snapshot_dropbox_sync
  alias: Dropbox Snapshot Sync (4am)
  trigger: 
    - platform: time
      at: '4:00:00'
  action:
    - service: hassio.addon_stdin
      data_template:
        addon: 7be23ff5_dropbox_sync
        input: {"command":"upload"}

- id: a_mqtt_state_sync
  alias: "Sonoff MQTT State Sync"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "sonoffs/cmnd/power"
        payload: "" 