#### Lights.yaml ####

# RFXCOM 433 Sensors
- platform: rfxtrx
  automatic_add: False
  devices:
### Flamerite Fire ###
    0b110008015b6eff03010f80:
      name: flamerite_dimmer1
    0b11000d015b6eff04010f80:
      name: flamerite_dimmer2
### Lightwave RF Dimmer Lights ###
    0a1400b303922201010060:
      name: lwrf_diningroom_main
    0a1400ac03922101010060:
      name: lwrf_livingroom_main
    0a14000a03922501010070:
      name: lwrf_morgan_main

- platform: flux_led
  automatic_add: False
  devices:
    192.168.200.31:
      name: wifi_ufo_1
      mode: "rgbw"
    192.168.200.32:
      name: wifi_ufo_2
      mode: "rgbw"
    192.168.200.33:
      name: wifi_ufo_3
      mode: "rgbw"
    192.168.200.34:
      name: wifi_ufo_4
      mode: "rgbw"
