#### Switches.yaml ####
- platform: rfxtrx
  automatic_add: false
  devices:
### Lightwave RF ###
    0a140000f4f6ad01000080:
      name: lwrf_conservatory_1
    0a140002f4f6ad02000080:
      name: lwrf_conservatory_2
    0a14001203922102000060:
      name: lwrf_livingroom_standard_lamp
    0a14000103922103010070:
      name: lwrf_displaycabinetlight
    0a14009503922104010060:
      name: lwrf_waxburner
    0a14000df50db80d000070:
      name: lwrf_diningroom_rennie_mac_lamp
    0a14000803922301010080:
      name: lwrf_hall_socket_1
    0a14001303922302010080:
      name: lwrf_hall_socket_2
### Flamerite Fire ###
    0b11000a015b6eff01010f80:
      name: flamerite_power
    0b11000f015b6eff02010f70:
      name: flamerite_heat

- platform: mqtt
  name: "Sonoff Loft Fan Power"
  state_topic: "stat/sonoff_loft_fan/POWER"
  command_topic: "cmnd/sonoff_loft_fan/POWER"
  availability_topic: "tele/sonoff_loft_fan/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
