homeassistant:
  customize:
    switch.tp_hs110_8:
      friendly_name: "Tumble Dryer"
      icon: mdi:tumble-dryer

switch:
  - platform: tplink
    host: 192.168.200.28 # DHCP reservation
    name: tp_hs110_8

input_select:
  dryer_status:
    name: Tumble Dryer Status
    options:
      - Idle
      - Drying
      - Finishing
    initial: Idle

sensor:
  - platform: template
    sensors:
      tp_hs110_8_power:
        value_template: '{{ states.switch.tp_hs110_8.attributes["current_power_w"].split(" ")[0]}}'
        unit_of_measurement: 'W'
        friendly_name: "Tumble Dryer Power"
  - platform: template
    sensors:
      dryer_status:
        value_template: '{{ states.input_select.dryer_status.state}}'
        friendly_name: 'Tumble Dryer Status'

automation:
# When we detect power being drawn from the dryer, above 250W,
# mark the dryer as using started
  - alias: Set dryer active when power detected
    trigger:
      - platform: numeric_state
        entity_id: sensor.tp_hs110_8_power
        above: 250
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.dryer_status
          state: Idle
        - condition: state
          entity_id: input_select.dryer_status
          state: Finishing
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_status
          option: Drying

# When the power level drops below 250W, and the dryer is set to
# the 'Drying' state, mark the dryer as Finishing
  - alias: Set dryer drying when power drops
    trigger:
      - platform: numeric_state
        entity_id: sensor.tp_hs110_8_power
        below: 250
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.dryer_status
          state: Drying
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_status
          option: Finishing

# Once the dryer status has been 'Finishing' for 5 minutes, set to idle
  - alias: Set Dryer to idle
    trigger:
      - platform: state
        entity_id: input_select.dryer_status
        to: Finishing
        for:
          minutes: 5
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.dryer_status
          state: Finishing
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_status
          option: Idle
      - service: notify.ios_martins_iphone
        data:
          message: 'The Dryer has finished and is ready to be emptied!'
          title: 'Tumble Dryer Update'
