##################################################
## Customize
##################################################
homeassistant:
  customize_glob:
    sensor.breaches*:
      icon: mdi:email-alert

group:
  have_i_been_pawned:
    name: HaveIBeenPwned
    entities:
      - !secret sensor_hibp_email1
      - !secret sensor_hibp_email2
      - !secret sensor_hibp_email3
      - !secret sensor_hibp_email4
      - !secret sensor_hibp_email5
      - !secret sensor_hibp_email6
      - !secret sensor_hibp_email7
      - !secret sensor_hibp_email8
      - !secret sensor_hibp_email9
  automation_package_haveibeenpwned:
    name: Have I Been Pwned
    entities:
      - automation.have_i_been_pwned_change

##################################################
## Components/Sensors
##################################################
sensor:
  - platform: haveibeenpwned
    email:
      - !secret hibp_email1
      - !secret hibp_email2
      - !secret hibp_email3
      - !secret hibp_email4
      - !secret hibp_email5
      - !secret hibp_email6
      - !secret hibp_email7
      - !secret hibp_email8
      - !secret hibp_email9

##################################################
## Automation
##################################################
automation:
- alias: Have I Been Pwned Change
  trigger:
    - platform: numeric_state
      above: 0
      entity_id: 
        - !secret sensor_hibp_email3
        - !secret sensor_hibp_email4
        - !secret sensor_hibp_email5
    - platform: numeric_state
      above: 1
      entity_id:
        - !secret sensor_hibp_email2
        - !secret sensor_hibp_email9
    - platform: numeric_state
      above: 2
      entity_id:
        - !secret sensor_hibp_email6
    - platform: numeric_state
      above: 3
      entity_id:
        - !secret sensor_hibp_email7
    - platform: numeric_state
      above: 4
      entity_id:
        - !secret sensor_hibp_email1
        - !secret sensor_hibp_email8
  action:
    service: notify.martin
    data_template:
      message: "Warning - HaveIbeenPwned detected {{ trigger.to_state.attributes.friendly_name }}"
