homeassistant:
  customize:
    light.wifi_ufo_1:
      friendly_name: "Desk"
      icon: mdi:led-strip
    light.wifi_ufo_2:
      friendly_name: "Window"
      icon: mdi:led-strip
    light.wifi_ufo_3:
      friendly_name: "Rear Wall"
      icon: mdi:led-strip
    light.wifi_ufo_4:
      friendly_name: "Bed"
      icon: mdi:led-strip

light:
  - platform: flux_led
    automatic_add: False
    devices:
      192.168.200.31:
        name: wifi_ufo_1
        mode: "rgbw"
      192.168.200.32:
        name: wifi_ufo_2
        mode: "rgbw"
      192.168.200.33:
        name: wifi_ufo_3
        mode: "rgbw"
      192.168.200.34:
        name: wifi_ufo_4
        mode: "rgbw"   