##################################################
## Customize
##################################################
# homeassistant:
#   customize:

##################################################
## Components/Sensors
##################################################
sensor:
  # https://www.home-assistant.io/components/sensor.pi_hole/
  - platform: pi_hole
    host: !secret pihole_host
    monitored_conditions:
      - ads_blocked_today
      - dns_queries_today
      - unique_clients

##################################################
## Automation
##################################################
# automation:

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_dns_queries_today
      - sensor.pi_hole_unique_clients

history:
  include:
    entities:
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_dns_queries_today
      - sensor.pi_hole_unique_clients
