homeassistant:
  customize:
    sensor.speedtest_download:
      icon: mdi:cloud-download
    sensor.speedtest_upload:
      icon: mdi:cloud-upload
sensor:
  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload