##################################################
## Components/Sensors
##################################################
sensor:
  - platform: waze_travel_time
    name: "To Work"
    origin: !secret waze_home
    destination: !secret waze_work
    region: "EU"

  - platform: waze_travel_time
    name: "To Home"
    origin: !secret waze_work
    destination: !secret waze_home
    region: "EU"

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.to_home
      - sensor.to_work

history:
  include:
    entities:
      - sensor.to_home
      - sensor.to_work
