##################################################
## Customize
##################################################
homeassistant:
  customize:
    binary_sensor.zha_025370bc_1_6:
      icon: mdi:door
      friendly_name: "Front Door"
    binary_sensor.zha_0275335b_1_6:
      icon: mdi:door
      friendly_name: "Back Door"
    binary_sensor.zha_02753210_1_6:
      icon: mdi:door
      friendly_name: "Garage Interior Door"
    binary_sensor.lumi_lumi_sensor_magnet_03033d99_1_6:
      icon: mdi:window-open
      friendly_name: "Morgan - Window"
    sensor.lumi_lumisens_02378aca_1_1029:
      icon: mdi:water-percent
      friendly_name: "ZigBee TH1 - Humidty"
    sensor.zha_02378aca_1_1026:
      friendly_name: "ZigBee TH1 - Temperature"
    zha.zha_lumi_lumi_sensor_ht_02378aca:
      icon: mdi:cellphone-wireless
      friendly_name: "ZigBee TH1"
    zha.zha_lumi_lumi_sensor_magnet_aq2_025370bc:
      icon: mdi:cellphone-wireless
      friendly_name: "Zigbee - Front Door"
    zha.zha_lumi_lumi_sensor_magnet_aq2_0275335b:
      icon: mdi:cellphone-wireless
      friendly_name: "Zigbee - Back Door"
    zha.zha_lumi_lumi_sensor_magnet_aq2_02753210:
      icon: mdi:cellphone-wireless
      friendly_name: "Zigbee - Garage Interior Door"
    zha.lumi_lumi_sensor_magnet:
      icon: mdi:cellphone-wireless
      friendly_name: "Zigbee - Morgan Window"


##################################################
## Automation
##################################################

# If back door open set heating mode to Eco, set to heat when closed.
# This originally stored the state and restored it, however this seemed unrealible, maybe a Nest API rate limit issue.
# To reduce the chance of hitting Nest API rate limits, door needs to be in open for 2 mins before a change made.
automation:
  - alias: Door Open - Set heating mode to eco
    trigger:
      - platform: state
        entity_id: binary_sensor.zha_0275335b_1_6  # Back door
        to: 'on'
        for:
          minutes: 2
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.hallway_house
          operation_mode: 'eco'
  
  - alias: Door Closed - Reset heating mode
    trigger:
      - platform: state
        entity_id: binary_sensor.zha_0275335b_1_6 # Back door
        to: 'off'
    action:
      - service: climate.set_operation_mode
        data_template:
          entity_id: climate.hallway_house
          operation_mode: 'heat'

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.lumi_lumisens_02378aca_1_1029 # Humidity
      - sensor.zha_02378aca_1_1026 # Temperature
      - zha.zha_lumi_lumisensor_ht_02378aca # Temp/Humidity sensor online status
      - binary_sensor.zha_025370bc_1_6 # Magnetic Front Door
      - binary_sensor.zha_0275335b_1_6 # Magnetic Back Door
      - binary_sensor.zha_02753210_1_6 # Magnetic Garage Interior Door
      - binary_sensor.lumi_lumi_sensor_magnet_03033d99_1_6 # Morgan Window

history:
  include:
    entities:
      - sensor.lumi_lumisens_02378aca_1_1029 # Humidity
      - sensor.zha_02378aca_1_1026 # Temperature
      - zha.zha_lumi_lumisensor_ht_02378aca # Temp/Humidity sensor online status
      - binary_sensor.zha_025370bc_1_6 # Magnetic Front Door
      - binary_sensor.zha_0275335b_1_6 # Magnetic Back Door
      - binary_sensor.zha_02753210_1_6 # Magnetic Garage Interior Door
      - binary_sensor.lumi_lumi_sensor_magnet_03033d99_1_6 # Morgan Window
