##################################################
## Customize
##################################################
homeassistant:
  customize:
    binary_sensor.zha_025370bc_1_6:
      icon: mdi:door
      friendly_name: "Front Door"
    binary_sensor.zha_0275335b_1_6:
      icon: mdi:door
      friendly_name: "Back Door"
    binary_sensor.zha_02753210_1_6:
      icon: mdi:door
      friendly_name: "Garage Interior Door"
    sensor.lumi_lumisens_02378aca_1_1029:
      icon: mdi:water-percent
      friendly_name: "ZigBee TH1 - Humidty"
    sensor.zha_02378aca_1_1026:
      friendly_name: "ZigBee TH1 - Temperature"
    zha.zha_lumi_lumisensor_ht_02378aca:
      icon: mdi:cellphone-wireless
      friendly_name: "ZigBee TH1"
    zha.zha_lumi_lumisensor_magnetaq2_025370bc:
      icon: mdi:cellphone-wireless
      friendly_name: "Zigbee - Front Door"
    zha.zha_lumi_lumisensor_magnetaq2_0275335b:
      icon: mdi:cellphone-wireless
      friendly_name: "Zigbee - Back Door"
    zha.zha_lumi_lumisensor_magnetaq2_02753210:
      icon: mdi:cellphone-wireless
      friendly_name: "Zigbee - Garage Interior Door"

##################################################
## Components/Sensors
##################################################
input_select:
  heating_previous_state:
    name: Heating Previous State
    options:
      - 'off'
      - 'eco'
      - 'heat'

sensor:
  - platform: template
    sensors:
      heating_previous_state:
        value_template: "{{ states.input_select.heating_previous_state.state }}"
        friendly_name: "Heating Previous State"

##################################################
## Automation
##################################################

# If back door open set heating mode to Eco, reset state when closed.
# To reduce the chance of hitting Nest API rate limits,
# door needs to be in open for 2 mins before a change made.
automation:
  - alias: Door Open - Set heating mode to eco
    trigger:
      - platform: state
        entity_id: binary_sensor.zha_0275335b_1_6  # Back door
        to: 'on'
        for:
          minutes: 2
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.heating_previous_state
          option: '{{states.climate.hallway_house.state}}'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.hallway_house
          operation_mode: 'eco'
  
  - alias: Door Closed - Reset heating mode
    trigger:
      - platform: state
        entity_id: binary_sensor.zha_0275335b_1_6 # Back door
        to: 'off'
    action:
      - service: climate.set_operation_mode
        data_template:
          entity_id: climate.hallway_house
          operation_mode: '{{ states("input_select.heating_previous_state") }}'

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.lumi_lumisens_02378aca_1_1029 # Humidity
      - sensor.zha_02378aca_1_1026 # Temperature
      - zha.zha_lumi_lumisensor_ht_02378aca # Temp/Humidity sensor online status
      - binary_sensor.zha_025370bc_1_6 # Magnetic Front Door
      - binary_sensor.zha_0275335b_1_6 # Magnetic Back Door
      - binary_sensor.zha_02753210_1_6 # Magnetic Garage Interior Door
      - zha.zha_lumi_lumisensor_magnetaq2_025370bc # Magnetic sensor online status Front Door
      - zha.zha_lumi_lumisensor_magnetaq2_0275335b # Magnetic sensor online status Back Door
      - zha.zha_lumi_lumisensor_magnetaq2_02753210 # Magnetic sensor online status Garage Interior Door
      - sensor.heating_previous_state

history:
  include:
    entities:
      - sensor.lumi_lumisens_02378aca_1_1029 # Humidity
      - sensor.zha_02378aca_1_1026 # Temperature
      - zha.zha_lumi_lumisensor_ht_02378aca # Temp/Humidity sensor online status
      - binary_sensor.zha_025370bc_1_6 # Magnetic Front Door
      - binary_sensor.zha_0275335b_1_6 # Magnetic Back Door
      - binary_sensor.zha_02753210_1_6 # Magnetic Garage Interior Door
      - zha.zha_lumi_lumisensor_magnetaq2_025370bc # Magnetic sensor online status Front Door
      - zha.zha_lumi_lumisensor_magnetaq2_0275335b # Magnetic sensor online status Back Door
      - zha.zha_lumi_lumisensor_magnetaq2_02753210 # Magnetic sensor online status Garage Interior Door
      - sensor.heating_previous_state
