##################################################
## Customize
##################################################
homeassistant:
  customize:
    # Aeotec Stick
    zwave.aeotec_zw090_zstick_gen5_eu:
      friendly_name: "Z-Wave Stick"
    
    # Aeotec Multisensor (Ironing Room)
    sensor.aeotec_zw100_multisensor_6_temperature:
      friendly_name: "Temperature (Ironing Room)"
    sensor.aeotec_zw100_multisensor_6_relative_humidity:
      friendly_name: "Humidity (Ironing Room)"
      icon: mdi:water-percent

    # Aeotec Multisensor (garage)
    sensor.aeotec_zw100_multisensor_6_temperature_2:
      friendly_name: "Temperature (Garage)"
    sensor.aeotec_zw100_multisensor_6_relative_humidity_2:
      friendly_name: "Humidity (Garage)"
      icon: mdi:water-percent

    # Fibaro Multi-Sensor (Loft)
    sensor.fibaro_system_fgms001zw5_motion_sensor_temperature:
      friendly_name: "Temperature (Loft)"
    sensor.fibaro_system_fgms001zw5_motion_sensor_burglar:
      friendly_name: "Loft Motion State"
      icon: mdi:walk
    sensor.fibaro_system_fgms001zw5_motion_sensor_luminance:
      friendly_name: "Loft Luminance"
      icon: mdi:theme-light-dark
    sensor.fibaro_system_fgms001zw5_motion_sensor_seismic_intensity:
      friendly_name: "Loft Seismic Intensity"

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.aeotec_zw100_multisensor_6_temperature
      - sensor.aeotec_zw100_multisensor_6_relative_humidity
      - sensor.aeotec_zw100_multisensor_6_burglar
      - sensor.aeotec_zw100_multisensor_6_temperature_2
      - sensor.aeotec_zw100_multisensor_6_relative_humidity_2
      - sensor.aeotec_zw100_multisensor_6_luminance_2
      - sensor.aeotec_zw100_multisensor_6_burglar_2
      - sensor.fibaro_system_fgms001zw5_motion_sensor_temperature

history:
  include:
    entities:
      - sensor.aeotec_zw100_multisensor_6_temperature
      - sensor.aeotec_zw100_multisensor_6_relative_humidity
      - sensor.aeotec_zw100_multisensor_6_burglar
      - sensor.aeotec_zw100_multisensor_6_temperature_2
      - sensor.aeotec_zw100_multisensor_6_relative_humidity_2
      - sensor.aeotec_zw100_multisensor_6_luminance_2
      - sensor.aeotec_zw100_multisensor_6_burglar_2
      - sensor.fibaro_system_fgms001zw5_motion_sensor_temperature
